services:
  postgres:
    container_name: postgres-sql-crud_clientes
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: marcio
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: crud_clientes
    volumes:
#      - postgres:/data/postgres
      - postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432

    networks:
      - spring-demo
    restart: unless-stopped
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local