spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crud_clientes
    username: postgres
    password: marcio
    driver-class-name: org.postgresql.Driver
#    hikari:
#      initialization-fail-timeout: 0

  jpa:
    hibernate:
      ddl-auto: validate # ou "create", "validate", "none" conforme o uso
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # opcional: logging mais limpo para SQL
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
